const MIN_USERNAME_LENGTH = 1;
const MAX_USERNAME_LENGTH = 32;

const MIN_LOGIN_LENGTH = 3;
const MAX_LOGIN_LENGTH = 32;

const MIN_PASSWORD_LENGTH = 3;
const MAX_PASSWORD_LENGTH = 64;

export {
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
  MIN_USERNAME_LENGTH,
  MAX_USERNAME_LENGTH,
  MIN_LOGIN_LENGTH,
  MAX_LOGIN_LENGTH,
};
